# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cosmetic_bot
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botnet

  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents:ro
      - ./chroma_db:/app/chroma_db
    depends_on:
      - db
    networks:
      - botnet

volumes:
  postgres_data:  # ← это именованный том, должен быть словарём (ключ: пустое значение)

networks:
  botnet:
    driver: bridge